import { Injectable } from '@angular/core';
import { ProduitModel } from '../models/produit.model';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

   products: ProduitModel[]
  constructor() {
    this.products  = [
       // food dog // food dog // food dog // food dog // food dog // food dog // food dog // food dog // food dog // food dog
    { id: 1, title: 'The Honest Kitchen Whole Food Clusters Whole Grain Chicken & Oat Dry Dog Food', price: 27.43, image: '', description: 'Chicken, oats, barley, chicken liver, carrots, eggs, ground flaxseed, broccoli, pumpkin, apples, natural chicken flavor, coconut oil, kale, chia seed, salmon oil, minerals [tricalcium phosphate, sodium chloride, potassium chloride, iron amino acid chelate, copper amino acid chelate, manganese amino acid chelate, zinc amino acid chelate, sodium selenite], fenugreek seed, dried kelp, taurine, L-carnitine, vitamins [vitamin A supplement, vitamin D3 supplement, vitamin E supplement, niacin supplement, folic acid, thiamine mononitrate (vitamin B1), riboflavin (vitamin B2), calcium pantothenate (vitamin B5), pyridoxine hydrochloride (vitamin B6), vitamin B12 supplement, choline chloride ], mixed tocopherols (a natural preservative), turmeric, dried bacillus coagulans fermentation product, rosemary extract.', si1: '', si2: '', si3: '', si4: '',category:'food dog' },
    { id: 2, title: 'The Honest Kitchen Whole Food Clusters Grain Free Beef Dry Dog Food', price: 34.29, image: '', description: 'Apples, bacillus coagulans, beef, beef liver, beta-carotene, broccoli, calcium carbonate, calcium pantothenate (vitamin B5), carrots, chia seed, coconut oil, copper amino acid chelate, crude fat, crude fiber, crude protein, dried bacillus coagulans fermentation product, dried kelp, eggs, fenugreek seed, folic acid, ground flaxseed, human grade, iron amino acid chelate, kale, lentils, manganese amino acid chelate, minerals, mixed tocopherols (a natural preservative), moisture, natural beef flavor, niacin supplement, peas, potatoes, pumpkin, pyridoxine hydrochloride (vitamin B6), riboflavin (vitamin B2), rosemary extract, salmon oil, sodium chloride, sodium selenite, taurine, thiamine mononitrate (vitamin B1), turmeric, vitamin A supplement, vitamin B12 supplement, vitamin D3 supplement, vitamin E supplement, vitamin E (min 140 IU/kg), zinc amino acid chelate.', si1: '', si2: '', si3: '', si4: '',category:'food dog' },
    { id: 3, title: 'The Honest Kitchen Whole Food Clusters Human Grade Dry Dog Food', price: 34.29, image: '', description: 'Turkey, potatoes, peas, lentils, carrots, eggs, ground flaxseed, turkey liver, broccoli, pumpkin, apples, coconut oil, natural turkey flavor, salmon oil, kale, chia seed, minerals [calcium carbonate, tricalcium phosphate, sodium chloride, iron amino acid chelate, copper amino acid chelate, manganese amino acid chelate, zinc amino acid chelate, sodium selenite], fenugreek seed, dried kelp, taurine, vitamins [vitamin A supplement, vitamin D3 supplement, vitamin E supplement, thiamine mononitrate (vitamin B1), riboflavin (vitamin B2), calcium pantothenate (vitamin B5), pyridoxine hydrochloride (vitamin B6), folic acid, vitamin B12 supplement, niacin supplement], mixed tocopherols (a natural preservative), turmeric, dried bacillus coagulans fermentation product, rosemary extract', si1: '', si2: '', si3: '', si4: '',category:'food dog' },
    { id: 4, title: 'JustFoodForDogs Frozen Fresh Dog Food, Complete Meal or Dog Food Topper, Beef & Russet Potato Human Grade Dog Food Recipe, 18 oz (Pack of 7)', price: 83.99, image: '', description: 'Beef, Potatoes, Sweet Potatoes, Green Beans, Carrots, Sunflower Oil, Beef Liver, Peas, Apples, Algae Oil, Dicalcium Phosphate, Calcium Carbonate, Salt, Magnesium Amino Acid Chelate, Taurine, L-Tryptophan, Choline Chloride, Zinc Amino Acid Chelate, Vitamin E Supplement, Selenium Yeast, Iron Amino Acid Chelate, Copper Amino Acid Chelate, Manganese Amino Acid Chelate, Cholecalciferol (source of Vitamin D3), Riboflavin, Thiamine, Potassium Iodide.', si1: '', si2: '', si3: '', si4: '' ,category:'food dog'},
    { id: 5, title: 'Blue Buffalo Life Protection Formula Adult Dry Dog Food, Helps Build and Maintain Strong Muscles, Made with Natural Ingredients, Beef & Brown Rice Recipe', price: 41.98, image: '', description: 'Deboned Beef, Chicken Meal, Brown Rice, Barley, Oatmeal, Peas, Chicken Fat (preserved with Mixed Tocopherols), Flaxseed (source of Omega 6 Fatty Acids), Natural Flavor, Fish Meal (source of Omega 3 Fatty Acids), Dried Tomato Pomace, Pea Protein, Salt, Direct Dehydrated Alfalfa Pellets, Potassium Chloride, Dried Chicory Root, Potatoes, Pea Fiber, Alfalfa Nutrient Concentrate, Calcium Carbonate, L-Threonine, Choline Chloride, DL-Methionine, preserved with Mixed Tocopherols, Sweet Potatoes, Carrots, Garlic, Taurine, Zinc Amino Acid Chelate, Zinc Sulfate, Vegetable Juice for color, Ferrous Sulfate, Glucosamine Hydrochloride, Yucca Schidigera Extract, Niacin, Calcium Pantothenate , Copper Sulfate, L-Ascorbyl-2-Polyphosphate , L-Lysine, Biotin, L-Carnitine, Vitamin A Supplement, Copper Amino Acid Chelate, Manganese Sulfate, Manganese Amino Acid Chelate, Thiamine Mononitrate , Riboflavin , Vitamin D3 Supplement, Vitamin B12 Supplement, Pyridoxine Hydrochloride , Calcium Iodate', si1: '', si2: '', si3: '', si4: '',category:'food dog' },
    { id: 6, title: 'Blue Buffalo Life Protection Formula Adult Small Breed Dry Dog Food, Supports High Energy Needs, Made with Natural Ingredients, Chicken & Brown Rice Recipe', price: 41.98, image: '', description: 'Deboned Chicken, Chicken Meal, Brown Rice, Oatmeal, Barley, Chicken Fat (preserved with Mixed Tocopherols), Flaxseed (source of Omega 3 & 6 Fatty Acids), Natural Flavor, Peas, Dried Tomato Pomace, Dried Yeast, Dried Egg Product, Salt, Potassium Chloride, Direct Dehydrated Alfalfa Pellets, Calcium Carbonate, Zinc Amino Acid Chelate, Zinc Sulfate, Vegetable Juice for color, Ferrous Sulfate, Vitamin E Supplement, Iron Amino Acid Chelate, Glucosamine Hydrochloride, Blueberries, Cranberries, Barley Grass, Parsley, Turmeric, Dried Kelp, Yucca Schidigera Extract, Niacin , Calcium Pantothenate , Copper Sulfate, Biotin, L-Ascorbyl-2-Polyphosphate , L-Lysine, Vitamin A Supplement, Copper Amino Acid Chelate, Manganese Sulfate, Manganese Amino Acid Chelate, Thiamine Mononitrate , Riboflavin , Vitamin D3 Supplement, Vitamin B12 Supplement, Pyridoxine Hydrochloride (Vitamin B6), Calcium Iodate, Folic Acid (Vitamin B9), Sodium Selenite, Oil of Rosemary.', si1: '', si2: '', si3: '', si4: '' ,category:'food dog'},
    { id: 7, title: 'Royal Canin Size Health Nutrition Small Adult Dry Dog Food', price: 26.49, image: '', description: 'Corn, chicken by-product meal, brewers rice, brown rice, corn gluten meal, chicken fat, natural flavors, dried plain beet pulp, wheat gluten, fish oil, vegetable oil, potassium chloride, calcium carbonate, salt, fructooligosaccharides, sodium tripolyphosphate, L-lysine, choline chloride, DL-methionine, monocalcium phosphate, vitamins [DL-alpha tocopherol acetate (source of vitamin E), L-ascorbyl-2-polyphosphate (source of vitamin C), biotin, D-calcium pantothenate, vitamin A acetate, pyridoxine hydrochloride (vitamin B6), niacin supplement, folic acid, thiamine mononitrate (vitamin B1), vitamin B12 supplement, riboflavin supplement, vitamin D3 supplement], trace minerals [zinc proteinate, zinc oxide, ferrous sulfate, manganese proteinate, manganous oxide, copper sulfate, calcium iodate, sodium selenite, copper proteinate], magnesium oxide, L-carnitine, rosemary extract, preserved with mixed tocopherols and citric acid.', si1: '', si2: '', si3: '', si4: '' ,category:'food dog'},
    { id: 8, title: 'IAMS Proactive Health Minichunks Adult Dry Dog Food with Lamb & Rice', price: 46.98, image: '', description: 'Lamb, Brewers Rice, Chicken By-Product Meal, Ground Whole Grain Barley, Ground Whole Grain Corn, Ground Whole Grain Sorghum, Corn Gluten Meal, Chicken Fat (preserved with Mixed Tocopherols), Chicken Meal, Dried Plain Beet Pulp, Natural Flavor, Brewers Yeast, Dried Egg Product, Flaxseed, Potassium Chloride, Caramel Color, Carrots, Fructooligosaccharides, Choline Chloride, Vitamins (Vitamin E Supplement, Ascorbic Acid, Calcium Pantothenate, Biotin, Thiamine Mononitrate (source of Vitamin B1), Vitamin B12 Supplement, Vitamin A Supplement, Niacin, Riboflavin Supplement (source of Vitamin B2), Pyridoxine Hydrochloride (source of Vitamin B6), Vitamin D3 Supplement, Folic Acid), Minerals (Ferrous Sulfate, Zinc Oxide, Sodium Selenite, Manganese Sulfate, Manganous Oxide, Potassium Iodide), Mixed Tocopherols (preservative), Citric Acid (preservative), Rosemary Extract', si1: '', si2: '', si3: '', si4: '',category:'food dog' },
    { id: 9, title: 'IAMS Proactive Health Minichunks Adult Dry Dog Food with Real Chicken', price: 46.98, image: '', description: ' Chicken, Ground Whole Grain Corn, Ground Whole Grain Sorghum, Chicken By-Product Meal, Dried Plain Beet Pulp, Natural Flavor, Flaxseed, Dried Egg Product, Chicken Fat (Preserved with Mixed Tocopherols), Caramel Color, Vitamins (Vitamin E Supplement, Ascorbic Acid, Calcium Pantothenate, Biotin, Thiamine Mononitrate (source of Vitamin B1), Vitamin B12 Supplement, Vitamin A Supplement, Niacin, Riboflavin Supplement (source of Vitamin B2), Pyridoxine Hydrochloride (source of Vitamin B6), Vitamin D3 Supplement, Folic Acid), Minerals (Ferrous Sulfate, Zinc Oxide, Sodium Selenite, Manganese Sulfate, Manganous Oxide, Potassium Iodide), Potassium Chloride, Carrot, Choline Chloride, Fructooligosaccharides, Calcium Carbonate, Mixed Tocopherols (Preservative), Rosemary Extract', si1: '', si2: '', si3: '', si4: '',category:'food dog' },
    { id: 10, title: 'Open Farm, Ancient Grains Dry Dog Food, Protein-Rich & Nutrient Dense, 90% Animal Protein Mixed with Non-GMO Fruits, Veggies and Superfoods, Grass-Fed Beef Recipe', price: 28.99, image: '', description: 'Beef, Oats, Ocean Whitefish Meal, Millet, Quinoa, Brown Rice, Coconut Oil, Herring Meal, Pumpkin, Natural Flavor, Carrots, Apples, Cranberries, Salmon Oil (source of DHA), Salt, Potassium Chloride, Dried Chicory Root, Choline Chloride, Vitamins (Vitamin E Supplement, Vitamin A Supplement, Niacin Supplement, Calcium Pantothenate, Riboflavin Supplement, Vitamin D3 Supplement, Thiamine Mononitrate, Vitamin B12 Supplement, Pyridoxine Hydrochloride, Folic Acid), Minerals (Zinc Proteinate, Iron Proteinate, Copper Proteinate, Manganese Proteinate, Selenium Yeast, Calcium Iodate), Taurine, Mixed Tocopherols (a preservative), Cinnamon, Turmeric, Rosemary Extract.', si1: '', si2: '', si3: '', si4: '',category:'food dog' },



    //toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog//toys dog
    { id: 11,category:'toys dog', title: 'Nylabone Customer Favorites Power Chew Toy Bundle for Dogs, Indestructible Dog Toys for Aggressive Chewers, Pack of 3 Dog Toys, Flavor Medley', price: 28.66, image: '', description: 'This Nylabone Dog Toy Bundle includes three of their most popular chew toys, built with durable material to withstand even the toughest chewers. Designed for large dogs over 50 pounds, the set features a textured chew ring, an ergonomic wishbone for easy holding, and engaging shapes to keep your pup entertained. Each toy is infused with irresistible flavors like beef, bison, and peanut butter, and includes ridges and nubs that help clean teeth as your dog chews. Perfect for keeping dogs busy, supporting dental health, and satisfying natural chewing instincts, these toys are made with love and purpose to keep your dog happy and healthy. ', si1: '', si2: '', si3: '', si4: '' },
    { id: 12,category:'toys dog', title: 'Potaroma Dog Puzzle Toy 2 Levels, Slow Feeder, Pup Food Treat Feeding Dispenser for IQ Training and Entertainment for All Breeds 4.2 Inch Height', price: 23.69, image: '', description: 'This 2-in-1 dog puzzle toy offers two challenge levels—start with level 1 by placing treats in base compartments and watch your pup nudge the lids to earn rewards. For level 2, add treats to the top and teach your dog to press the cover, releasing treats into the base. It doubles as a slow feeder, holding a large amount of food in the transparent top to reduce fast eating by over 10x. Designed for both large and small dogs, it stays stable with 4 non-slip rubber mats and a weighted base. Made from durable, food-grade PP, it\'s safe, easy to clean, and requires no assembly. The interactive design stimulates your dog\'s mind, reduces boredom, and curbs unwanted behaviors like chewing, barking, or digging. Size: 4.2 inches tall.', si1: '', si2: '', si3: '', si4: '' },
    { id: 13,category:'toys dog', title: 'WOOF Pupsicle - Long-Lasting Interactive Dog Toy to Keep Your Pup Distracted - Safe for Dogs - Low-Mess Design', price: 24.99, image: '', description: 'The Pupsicle is a durable, mess-free dog enrichment toy that opens for easy filling and cleaning—just unscrew the bottom, insert a treat, and hand it to your pup for 30+ minutes of distraction. Designed to reduce boredom, it\'s compatible with Pupsicle Refill Pops or DIY treats using a mold tray (sold separately). Its drool-catching slots and weighted base help keep playtime clean and stable, while dishwasher-safe materials make cleanup effortless. Made from natural rubber, it\'s safe for dogs of all sizes and built to last. The easy-fill design prevents spills, making treat time simple and stress-free. Created by Woof in Denver, this interactive toy keeps dogs happy and entertained while giving pet parents peace of mind.', si1: '', si2: '', si3: '', si4: '' },
    { id: 14,category:'toys dog', title: 'Original Snuggle Puppy Toys - Heartbeat Puppy for Dogs - Dog Plush for Anxiety Relief, Calming Aid, and Comfort Toy for Behavioral Training in Biscuit', price: 39.95, image: '', description: ' The Snuggle Puppy is the original dog enrichment toy designed to reduce stress, anxiety, and sleepless nights for puppies and dogs. Since 1997, it has comforted over 2 million pets and is a must-have for first-time dog owners. Built to last, it\'s made from safe, hypoallergenic materials and is machine washable, with a removable heat pack and Real-Feel Heartbeat for easy cleaning. The heartbeat mimics a mother\'s pulse, soothing dogs naturally and helping with crate training, separation anxiety, and fear of loud noises. It\'s perfect for both cuddly and playful pups and comes with two AAA batteries. With amazing reviews and our Pacified Pup Promise, we guarantee your satisfaction—or we’ll make it right. Designed for comfort, tested for safety, and backed by decades of trust, Snuggle Puppy is the ideal gift for any dog owner.', si1: '', si2: '', si3: '', si4: '' },
    { id: 15,category:'toys dog', title: 'Nylabone New Puppy Starter Kit, 2 Chew Toys and 1 Natural Treat for Puppies, Bacon & Chicken Flavor, Small - Up to 25 lbs, 3 Pack', price: 8.59, image: '', description: 'This chew toy duo is perfect for puppies, featuring a softer chicken-flavored bone for teething pups without adult teeth and a durable bacon-flavored bone for stronger chewers or those with adult teeth. Both toys support oral health by helping reduce plaque and tartar buildup as your puppy chews. Made in the USA with no added salt, artificial preservatives, or colors, they’re a healthy treat option for dogs. Designed for small breeds up to 25 lbs, each toy measures 4.5" long, 1" wide, and 1.75" high. With unique textures, shapes, and irresistible flavors, these trusted chew toys are created with heart and purpose to meet your pup’s needs at every stage.', si1: '', si2: '', si3: '', si4: '' },
    { id: 16,category:'toys dog', title: 'KIPRITII 25 Pack Various Puppy Dog Toys for Teething, Entertainment & Interaction, Puppy Chew Toys Pack with Rope Toys, Treat Balls and Dog Squeaky Toys for Puppy & Small Dogs', price:15.98, image: '', description: 'The KIPRITII 25-pack dog toy set offers a wide variety of fun, combining interactive, chew, training, and squeaky toys to keep your pup entertained 24/7 while protecting your furniture. Perfect for puppies and small dogs, the bundle includes 8 rope toys, 2 treat balls, 3 rubber toys, 3 squeaky plush toys, 1 flying disc, and 6 waste bag rolls with 2 dispensers. Great for both indoor and outdoor play, these toys help strengthen the bond between you and your dog or keep your pup happily occupied. Designed to support oral health and reduce boredom, the pack fulfills both pet and owner needs. Made with natural, pet-safe materials, each toy reflects KIPRITII’s commitment to quality and love for dogs, delivering joyful, enriching experiences for your furry companion. ', si1: '', si2: '', si3: '', si4: '' },
    { id: 17,category:'toys dog', title: 'Dog Interactive Treat Dispenser Toy, Food Puzzle Slow Feeder', price: 24.99, image: '', description: 'This interactive duck-shaped feeder toy keeps dogs engaged and active, even when alone. Designed as a press-type treat dispenser, it allows dogs to learn how to press the button to release small portions of food, promoting mental stimulation and independent play. Serving as a slow feeder, it helps reduce fast eating and supports better digestive health. Made from food-grade PP material, it’s both safe and appealing for your pup. The adorable design adds fun to mealtime while encouraging healthier habits. Backed by a 30-day return policy and a 1-year replacement guarantee, support is always available for any post-purchase concerns.', si1: '', si2: '', si3: '', si4: '' },
    { id: 18,category:'toys dog', title: 'Interactive Dog Toys with Motion Activated, Squeaky Dog Toy Active Rolling Ball Wicked Ball for Daily Training', price: 19.99, image: '', description: 'The Giociv motion-activated dog toy engages your pup with touch-activated movement, rolling for 5 minutes when poked or bitten, then entering a 1-hour standby mode. It starts with a 60-second motion test to catch your dog\'s attention and reactivates with interaction. Easily switch between fast (blue), slow (purple), and interactive (yellow) modes by pressing the power button inside the screw-off outer case. A strong rope or DIY tail can be added to enhance movement. Rechargeable via USB-C (2–3h charge), it includes a chirping sound by default to attract dogs, which can be muted by double-pressing the power button. Backed by a 12-month warranty and 24/7 customer support, the toy is designed for fun, stimulation, and hassle-free use.', si1: '', si2: '', si3: '', si4: '' },
    { id: 19,category:'toys dog', title: 'Pawstruck Large 5-6” Filled Dog Bones Variety Pack - Peanut Butter, Cheese & Bacon, Beef Flavors - Made in USA, Long Lasting Stuffed Femur Treat for Aggressive Chewers - Pack of 3, Packaging May Vary', price: 25.99, image: '', description: 'Natural Beef Bone. Filling: Corn Syrup, Chicken Broth, Chicken Meal, Sugar, Chicken Fat (preserved with Mixed Tocopherols), Salt, Propylene Glycol, Agar Agar, Bacon Bits (Textured Vegetable Protein, Vegetable Oil, Salt, Natural Flavor, Hydrolyzed Yeast, Hydrolyzed Vegetable Protein, Dextrose), Vegetable Glycerin, Cheese Flavor, Titanium Dioxide Color, Potassium Sorbate (A Preservative), Citric Acid, Lecithin, Natural Bacon Flavor, Sodium Benzoate (A Preservative), Yellow 5, Yellow 6', si1: '', si2: '', si3: '', si4: '' },
    { id: 20,category:'toys dog', title: 'Benebone Medium 4-Pack Dog Chew Toys for Aggressive Chewers, Made in USA, 60lbs and Under', price: 29.95, image: '', description: 'The Benebone Four-Pack offers four times the fun with durable chew toys that are tougher than real bones and built to last for weeks—even for super-chewers. Made with 100% real flavors like bacon, fish, and wood, these toys are crafted to satisfy your dog’s instincts with scents and tastes they love. Proudly made and sourced in the USA, Benebones are built tough to handle serious chewing. And if you ever have an issue, their friendly support team is ready to help, ensuring you and your pup stay happy.', si1: '', si2: '', si3: '', si4: '' },
    { id: 21,category:'toys dog', title: 'MON2SUN Dog Treats, Rawhide Twist Chicken Hide Sticks, Suitable for Puppy and Small Dogs, 5 Inch (Chicken, Pack of 40)', price: 19.79, image: '', description: 'These 5-inch chicken rawhide sticks are perfect for small and puppy dogs, with a 40-count pack offering lasting value. Made from real chicken breast wrapped around rawhide, they’re high in protein and low in fat, providing a nutritious and delicious treat. Roasted for flavor and manufactured under strict food safety standards, they contain no harmful ingredients. These chews promote dental health by helping reduce plaque and tartar while satisfying your dog’s natural chewing instincts. Backed by over 20 years of expertise and strict quality control, our support team is always ready to help if your pup isn\'t satisfied.', si1: '', si2: '', si3: '', si4: '' },
    { id: 22,category:'toys dog', title: 'BALANCE Orthopedic Dog Bed for Large Dogs, Comfortable Dog Sofa Beds with Removable Washable Cover & Waterproof Lining, Egg Crate Foam Dogs Couch for Pet Sleeping', price: 39.99, image: '', description: 'The BALANCE orthopedic dog bed features high-density egg crate foam to evenly distribute weight and relieve joint and muscle fatigue, while padded bolsters provide head and neck support for restful sleep. A waterproof layer protects the filling from spills and accidents, keeping the bed fresh and long-lasting. Made with non-shedding plush fabric, it offers a soft, warm surface your dog will love while helping keep your home cleaner. The removable, machine-washable cover makes cleaning easy, ensuring a hygienic space with minimal effort. A nonskid bottom keeps the bed securely in place on any floor, providing safety and stability for your pet.', si1: '', si2: '', si3: '', si4: '' },
    { id: 23,category:'toys dog', title: 'Wicker pet Bed Rattan Dog Sofa Bed Outdoor Indoor Water Resistant', price: 0, image: '', description: 'This wicker dog bed is made from all-weather, handwoven PE rattan that’s waterproof, durable, and breathable, promoting airflow for your pet’s comfort. It includes a soft, cozy cushion to create a relaxing resting spot for your furry friend. Designed with anti-slip footpads and an elevated base, it offers enhanced stability and security. Stylish and versatile, it’s perfect for both indoor and outdoor use—whether in the living room, patio, garden, or balcony—making it an ideal retreat for your pet anywhere in your home.', si1: '', si2: '', si3: '', si4: '' },





    //health and suppllies dog //health and suppllies dog //health and suppllies dog //
    { id: 24,category:'health and suppllies dog', title: 'Purina Pro Plan Veterinary Supplements Calming Care - Calming Dog Supplements - 30 ct. Box', price: 0, image: '', description: 'Purina Calming Care is the #1 veterinarian-recommended probiotic supplement for dogs (Kantar Veterinary Tracker, 2021), designed to support calm behavior in anxious pets. This calming powder helps reduce signs of stress like excessive barking, jumping, pacing, and spinning. It aids dogs in coping with stressors such as separation, unfamiliar visitors, loud noises, or changes in routine. Formulated with beneficial probiotics, it also promotes a healthy emotional state, supports immune health, and helps maintain positive cardiac activity during stressful situations—making it an ideal daily supplement for overall well-being.', si1: '', si2: '', si3: '', si4: '' },
    { id: 25,category:'health and suppllies dog', title: 'Seresto Large Dog Vet-Recommended Flea & Tick Treatment & Prevention Collar for Dogs Over 18 lbs. | 8 Months Protection', price: 59.98, image: '', description: 'The Seresto flea and tick collar offers vet-recommended, premium protection for dogs and puppies without the high price tag. It provides long-lasting defense, killing and repelling fleas and ticks for up to 8 continuous months. As the #1 veterinarian-recommended flea and tick collar*, it begins working within 24 hours, eliminating pests by contact—no biting required. This hassle-free, non-greasy, and easy-to-use solution keeps your dog protected and comfortable, making it a convenient and effective choice for year-round pest control.', si1: '', si2: '', si3: '', si4: '' },
    { id: 26,category:'health and suppllies dog', title: 'FRONTLINE Plus Flea and Tick Treatment for Large Dogs Up to 45 to 88 lbs. 3 Treatments', price: 39.98, image: '', description: 'FRONTLINE Plus for Dogs is a fast-acting, waterproof topical treatment that kills fleas, flea eggs, larvae, ticks, and lice, helping protect against Lyme disease and breaking the flea life cycle. Formulated with fipronil and (S)-methoprene, it provides powerful monthly protection by eliminating existing pests and preventing new infestations. Trusted for over 20 years, it\'s safe for puppies 8 weeks and older, weighing 5 lbs or more, and is easy to apply with one monthly dose. FRONTLINE also offers a formula for cats and kittens, making it easy to protect all pets in your household. For best results, treat all pets monthly and subscribe for year-round, uninterrupted protection with FRONTLINE Plus.', si1: '', si2: '', si3: '', si4: '' },
    { id: 27,category:'health and suppllies dog', title: 'FRONTLINE Plus Flea and Tick Treatment for Small Dogs Upto 5 to 22 lbs., 3 Treatments', price: 39.98, image: '', description: 'FRONTLINE Plus for Dogs is a fast-acting, waterproof flea and tick topical treatment that kills fleas, eggs, larvae, ticks, and lice—helping protect against Lyme disease. Formulated with fipronil and (S)-methoprene, it breaks the flea life cycle by targeting all stages of infestation. Trusted for over 20 years, it\'s safe for puppies 8 weeks and older, weighing 5 lbs or more, and offers 30 days of protection with one easy monthly dose. Also available for cats and kittens 8 weeks and older, FRONTLINE Plus allows multi-pet households to stay fully protected. Monthly treatment of all pets helps prevent new infestations. Subscribe and save for convenient, year-round protection without ever running out.', si1: '', si2: '', si3: '', si4: '' },
    { id: 28,category:'health and suppllies dog', title: 'Flea and Tick Prevention for Dogs Chewables - 170 Treats - Natural Dog Flea and Tick Treatment Chewable Supplement - Oral Pills - All Breeds & Ages', price: 23.97, image: '', description: 'Protect your dog naturally with our flea and tick prevention chews, a safe and itch-free alternative to harsh chemical treatments. These chicken-flavored chewables are easy to administer daily, helping build up effective protection levels in your dog’s system. Suitable for all breeds and ages—from tiny pups to large dogs—our chews offer broad, gentle protection. Formulated by veterinarians and made in the USA in an FDA-registered facility, they deliver trusted quality. Say goodbye to messy topicals and enjoy hassle-free, tasty prevention that keeps your furry friend comfortable and pest-free year-round.', si1: '', si2: '', si3: '', si4: '' },
    { id: 29,category:'health and suppllies dog', title: 'Yaya Organics Tick Ban | Extra Strength Tick Repellent Made with Essential Oils and All Natural, DEET Free Ingredients | Proven Effective, Safe for Adults, Kids and Dogs | 4 Ounce 2 Pack', price: 0, image: '', description: 'Tick Ban is an all-natural, DEET-free tick repellent made with certified organic, non-GMO plant-based ingredients like soybean oil, castor oil, and essential oils of cedarwood, peppermint, rosemary, geranium, lemongrass, and thyme. Safe and non-toxic, it can be used on skin, clothing, and gear, making it ideal for outdoor adventures like hiking, biking, camping, and travel. Family-friendly and suitable for adults, kids, dogs, and even horses, it offers reliable protection without harsh chemicals. Packaged in a reusable, eco-friendly aluminum spray bottle, it features a fresh herbal scent that repels ticks, flies, gnats, and more. Made in the USA, Tick Ban lets you enjoy the outdoors while it keeps the bugs away.' , si1: '', si2: '', si3: '', si4: '' },
    { id: 30,category:'health and suppllies dog', title: 'PetArmor Plus Flea and Tick Prevention for Dogs, Dog Flea and Tick Treatment, 6 Doses, Waterproof Topical, Fast Acting', price: 39.93, image: '', description: 'PetArmor Plus is a fast-acting, waterproof flea and tick treatment for dogs that kills fleas, flea eggs, larvae, ticks, and chewing lice for up to 30 days per application. Formulated with fipronil and (S)-methoprene—the same active ingredients as FRONTLINE Plus—it starts working within 24 hours to eliminate pests. Unlike some treatments, PetArmor Plus breaks the flea life cycle by targeting eggs and larvae to prevent re-infestation. Each easy-to-use dose provides full-body protection from nose to tail, and a 6-dose pack ensures up to six months of long-lasting coverage. Trusted and vet-quality, it\'s an effective solution for year-round flea and tick control.', si1: '', si2: '', si3: '', si4: '' },
    { id: 31,category:'health and suppllies dog', title: 'Capstar(nitenpyram) for Dogs Fast-Acting Oral Flea Treatment for Dogs 2-25 lbs, Vet-Recommended Medication Tablets Start Killing in 30 Minutes, 6 Doses', price: 39.98, image: '', description: 'CAPSTAR is a fast-acting oral flea treatment for small dogs, starting to kill adult fleas within just 30 minutes. With one dose, you can quickly see results as fleas begin to fall off your pet. Safe for dogs and puppies 4 weeks and older, weighing 2–25 pounds, it’s a convenient, over-the-counter solution requiring no prescription. If reinfestation occurs, CAPSTAR can be safely given once daily as needed, offering quick relief and flexible use. This 57 mg formula is a reliable choice for fast, effective flea control.', si1: '', si2: '', si3: '', si4: '' },
    { id: 32,category:'health and suppllies dog', title: 'Activate II Flea and Tick Prevention for Dogs | 4 Count | 4 Months Flea Treatment', price: 26.97, image: '', description: 'Activate II is a fast-acting, vet-approved flea and tick treatment for dogs, using the same active ingredients as K9 Advantix II—Imidacloprid, Permethrin, and Pyriproxyfen. This waterproof topical solution repels and kills fleas and ticks on contact, preventing bites and potential diseases. It also stops infestations by breaking the flea life cycle, with the insect growth regulator beginning to kill eggs and larvae within 12 hours. Easy to apply at the base of your dog’s neck, each dose offers 30 days of continuous protection. Made in the USA with guaranteed results, Activate II includes four monthly doses for lasting defense.', si1: '', si2: '', si3: '', si4: '' },
    { id: 33,category:'health and suppllies dog', title: 'Wondercide - Flea, Tick & Mosquito Spray for Pets and Home with Natural Essential Oils - Killer, Control, Prevention, Treatment - Lemongrass 16 oz', price: 26.99, image: '', description: 'This plant-powered flea, tick, and mosquito spray uses natural essential oils—cedar, lemongrass, and sesame—to kill pests on contact and prevent 98–100% of infestations by eliminating eggs, larvae, and adults. Made with a gentle, non-harsh formula, it’s safe for dogs, cats, and pets of all ages when used as directed, including puppies, kittens, and seniors. The 3-in-1 solution can be used directly on pets, in their environment, and throughout the home on carpets, furniture, bedding, and flooring. It offers a refreshing lemongrass scent while repelling pests in spaces like kennels or condos. Cruelty-free and made in the USA with globally sourced ingredients, this vet-trusted spray provides a safe, effective alternative to pills, collars, and drops for total flea and tick protection.', si1: '', si2: '', si3: '', si4: '' },
    { id: 34,category:'health and suppllies dog', title: 'Ear Mite Treatment For Dogs and Cats Over 12 Weeks, Kills Ear Mites On Contact, Relief For Dogs and Cats Suffering From Ear Mites, Soothing Aloe and Lanolin Formula', price: 0, image: '', description: 'Adams Ear Mite Treatment effectively kills ear mites on contact and is safe for use on dogs and cats 12 weeks and older. Formulated with pyrethrins and piperonyl butoxide, it also contains soothing aloe and lanolin to ease irritated skin. Designed for daily use over 7–10 days, the treatment can be repeated after two weeks if needed. The easy-to-use applicator makes ear care simple and stress-free. Trusted since 1975, Adams provides proven pest control solutions for pets, homes, and yards. For questions or support, consumers can easily reach the Adams customer care team through their website.', si1: '', si2: '', si3: '', si4: '' },
    { id: 35,category:'health and suppllies dog', title: 'Pet MD - Dog Ear Cleaner Wipes - Otic Cleanser for Dogs to Stop Ear Itching, and Infections with Aloe and Eucalyptus', price: 14.99, image: '', description: 'These advanced, alcohol-free ear wipes are designed to gently clean, deodorize, and dry your dog’s ears while reducing wax buildup and removing debris. Safe for regular use, they help prevent infections and minimize foul odors, keeping your dog happy and healthy without medication. Each pack includes 100 soothing, non-irritating disposable wipes suitable for dogs over 12 weeks old. Made in the USA in federally regulated facilities, they offer a convenient and effective way to maintain your pet’s ear hygiene with trusted quality and safety.', si1: '', si2: '', si3: '', si4: '' },






    //clothes dog //clothes dog//clothes dog//clothes dog//clothes dog//clothes dog//clothes dog//clothes dog//clothes dog//clothes dog
    { id: 36,category:'clothes dog', title: 'Turtleneck Knitted Knitwear for Pet,Easy On Doggie Sweatshirt Dog Sweater', price: 34.99, image: '', description: 'This cozy turtleneck dog sweater is made from soft, stretchable acrylic yarn to keep pets of all sizes warm and comfortable in cold weather. Designed with sleeves and a high belly cut for easy potty breaks, the pullover style makes it simple to put on and take off. The snug fit wraps the neck, chest, and belly for full warmth, while the neutral solid color adds a classic, stylish look suitable for male and female dogs. Perfect for holidays or daily wear, it’s great for all occasions—birthdays, Christmas, Halloween, or just everyday warmth. Available in multiple sizes and colors to fit small to extra-large breeds, including Dobermans and Rottweilers.', si1: '', si2: '', si3: '', si4: '' },
    { id: 37,category:'clothes dog', title: 'PUPTECK Dog Hoodie Puppy Sweatshirt Warm Dog Sweater Winter Clothes Cold Weather Coats', price: 16.99, image: '', description: 'This cozy dog hoodie is available in 7 sizes and 8 colors, making it a perfect fit for small, medium, and large breeds. Made from soft lambswool and fleece, it keeps your pet warm with a stylish design and a windproof hood—ideal for chilly autumn, winter, or spring days. Stretchy fabric at the neck, cuffs, and hem ensures a comfy fit that’s easy to slip on and off, allowing your dog to move freely and go potty without hassle. A built-in leash hole makes it convenient for walks, hikes, or outdoor adventures. Plus, a cute little back pocket adds charm and practicality, perfect for storing keys, treats, or poop bags. Be sure to measure your dog for the best fit, as sizing may vary by brand.', si1: '', si2: '', si3: '', si4: '' },
    { id: 38,category:'clothes dog', title: 'ROZKITCH Dog Winter Coat Soft Fleece Pullover Pajamas, Pet Windproof Warm Cold Weather Jacket Vest Cozy Jumpsuit Apparel Outfit Clothes', price: 41.99, image: '', description: 'This full-body dog coat is made from thick, soft polar fleece that’s warm, breathable, and resistant to shedding or pilling—perfect for keeping dogs cozy in cold weather. Designed with a high turtleneck collar that can be rolled up or down, it features a drawstring for an adjustable fit around the neck. A long back zipper and elastic cuffs make it easy to slip on and off, while drawstrings at the neck and chest enhance fit and insulation. The four-legged design offers greater coverage and warmth than traditional two-legged coats, making it ideal for outdoor activities like walking, jogging, or hiking. Available in sizes 2XS to 4XL, it\'s suited for all breeds from tiny Chihuahuas to large Labs and Dobermans.', si1: '', si2: '', si3: '', si4: '' },
    { id: 39,category:'clothes dog', title: 'Turtleneck Doggy Sweatshirt', price: 30.99, image: '', description: 'This stylish dog sweater is designed for dogs of all sizes—from small to XXL—and comes in twelve versatile colors to suit every pup’s personality. Made from soft, stretchable acrylic yarn, it offers cozy warmth and comfort, perfect for chilly days. The turtleneck design and full sleeves provide snug coverage for the neck, chest, and belly, while a high-cut belly ensures easy potty breaks. Its pullover style makes it easy to put on and take off, making it ideal for daily wear or special occasions like birthdays, Christmas, Halloween, and more. Whether you have a tiny pup or a large breed like a Lab or Golden Retriever, this fashionable and functional sweater is a must-have for keeping your furry friend warm and looking adorable.', si1: '', si2: '', si3: '', si4: '' },
    { id: 40,category:'clothes dog', title: 'Spark Paws Dog Cooling Vest - Summer Heat Relief, Lightweight, SPF 50 UV Sun Protection', price: 33.00, image: '', description: 'The Chilltech Cooling Vest is a safe, effective solution for keeping dogs of all sizes cool in hot weather. Made from lightweight, chemical-free materials, it uses advanced evaporative technology—just wet, wring, and wear for instant relief. For extra cooling, the vest can be frozen before use. It offers up to 60 minutes of cooling, is breathable and flexible for comfort, and features SPF 50 UV protection plus reflective strips for added safety. Easy to put on with side-release buckles, it’s perfect for summer walks, heatwaves, or outdoor adventures—just re-wet to refresh the cooling effect. Available in various sizes and colors.', si1: '', si2: '', si3: '', si4: '' },
    { id: 41,category:'clothes dog', title: 'Dog Raincoat, Waterproof Dog Rain Coats for Large Dogs, Lightweight Rain Jacket, Adjustable 4 Legs Pet Poncho with Hood, Snow-Proof Dog Vest Rainwear, Rain Clothes Apparel with Leash Hole', price: 26.99, image: '', description: 'This waterproof dog raincoat is made from 100% lightweight, waterproof fabric to keep dogs dry, clean, and comfortable in wet weather. Designed for all sizes and breeds, it features a button-closed belly and hood to protect your dog’s head and body from rain. The adjustable straps and four-leg design ensure a secure, personalized fit with full-body coverage and a large potty area. It\'s easy to clean—just wipe it down—and folds for convenient storage. Ideal for rainy walks or outdoor adventures, it suits everything from small pups to large breeds like Labs and Shepherds.', si1: '', si2: '', si3: '', si4: '' },
    { id: 42,category:'clothes dog', title: 'ROZKITCH Dog Winter Coat Soft Fleece Pullover Pajamas, Pet Windproof Warm Cold Weather Jacket Vest Cozy Jumpsuit Apparel Outfit Clothes', price: 34.99, image: '', description: 'This full-body dog coat, available in a variety of sizes (2XS–4XL) and colors, is crafted from thick polar fleece to provide maximum warmth, softness, and comfort during cold seasons. The adjustable high turtleneck collar can be rolled up or down, offering extra neck protection and versatility. Designed with a back zipper and elastic cuffs, it\'s easy to slip on and off, while drawstrings at the neck and chest ensure a snug, cozy fit. The four-leg coverage enhances insulation and protects against chilly winds, making it ideal for jogging, hiking, or everyday walks. Suitable for all dog breeds and sizes, from tiny pups to large companions.', si1: '', si2: '', si3: '', si4: '' },
    { id: 43,category:'clothes dog', title: 'TONY HOBY Female/Male Pet Dog Pajamas Stripes 4 Legged Dog pjs Jumpsuit Soft Cotton Dogs Clothes ', price: 18.99, image: '', description: 'These handmade cotton pet pajamas are soft, breathable, and perfect for dogs of all sizes and breeds. Featuring a four-legged design with an elastic waist and protective belly coverage, they provide warmth and comfort while helping with anxiety and recovery after surgery. Stylish snap fasteners make them easy to put on and take off, while the striped pattern adds a fashionable touch. Ideal for daily wear, sleeping, lounging in air-conditioned rooms, or photo sessions. Suitable for breeds like Poodles, Chihuahuas, Bulldogs, and more. Available in various sizes and colors to ensure the perfect fit.', si1: '', si2: '', si3: '', si4: '' },
    { id: 44,category:'clothes dog', title: 'Warm Dog Winter Clothes Cute Fruit Dog Coat Hoodies Fleece Pet Dogs Costume Jacket for French Bulldog Chihuahua Ropa para Perro', price: 9.89, image: '', description: 'This colorful fruit-themed dog coat adds a fun, fashionable touch to your pet’s wardrobe while keeping them warm and cozy. Made from soft fleece fabric with a hooded design, it’s perfect for chilly days and adds extra cuteness to your dog or cat’s look. Designed for comfort and warmth, it suits small to medium-sized pets, and comes in multiple sizes and colors to ensure a great fit. Whether for walks, photos, or lounging indoors, this adorable coat is both practical and stylish. Package includes one piece of dog clothing.', si1: '', si2: '', si3: '', si4: '' },
    { id: 45,category:'clothes dog', title: 'Tomkas Small Dog Sling Carrier - Classic Pocket & Classic Strap - for 3-10 lbs Pets', price: 12.99, image: '', description: 'The TOMKAS pet carrier sling is crafted from thick, soft, and durable fabric, offering a safe and cozy space for small pets up to 10 lbs. Its wide opening and adjustable safety belt make it easy to use and secure, while tough stitching and strong hardware ensure long-lasting performance. Designed with a large front pocket for essentials like keys, treats, and phones, it prevents items from falling out during use. Ideal for outings, travel, or vet visits, this carrier is perfect for elderly, injured, or post-surgery pets who need extra care. Though the shoulder strap is not adjustable in this entry-level model, it remains a practical, budget-friendly solution for anyone wanting to keep their furry friend close. Available in various sizes and colors for small dogs and cats.', si1: '', si2: '', si3: '', si4: '' },
    { id: 46,category:'clothes dog', title: 'Outward Hound Granby Splash Orange Dog Life Jacket', price: 15.99, image: '', description: 'This dog life jacket offers maximum flotation to support swimmers of all skill levels, with a smart design that includes a grab handle for easy lifting and a front float to keep your dog’s head above water. Bright colors and reflective trim ensure high visibility during swimming activities, enhancing safety. Adjustable straps provide a snug fit for dogs of all shapes and sizes, available from XS to XL. Made for comfort, safety, and ease of use, this life vest is perfect for boating, beach days, or pool play. Always supervise pets during use and replace the vest if damaged. Available in multiple colors and sizes to suit every dog.', si1: '', si2: '', si3: '', si4: '' },
    { id: 47,category:'clothes dog', title: '3 Pieces Pet Dog Hawaiian Costume, Includes Puppy Cool T-Shirts Summer Clothes, Funny Cute Dog Retro Fashion Sunglasses and a Colorful Wreath', price: 9.99, image: '', description: 'This fun pet costume set includes a Hawaiian-style T-shirt, fashion sunglasses, and a colorful wreath—perfect for daily wear, photo shoots, parties, or performances. The breathable cotton shirt helps protect pets from the sun and is machine washable. Stylish pet sunglasses made with resin lenses and alloy frames add charm, while the lightweight, non-toxic wreath offers comfort and a tropical flair. Designed to fit most pets, this outfit is available in various sizes and colors. It makes a great gift for birthdays, holidays, or summer beach outings, creating fun, memorable moments with your furry friend.', si1: '', si2: '', si3: '', si4: '' },
    { id: 48,category:'clothes dog', title: 'Jecikelon Winter Dog Hoodie Sweatshirts with Pockets Warm Dog Clothes', price: 9.99, image: '', description: 'This cozy woolen hoodie keeps pets warm and stylish with its solid color design and classic fit. Featuring a comfortable hood and handy pocket, it\'s perfect for adding charm while keeping your dog snug. Ideal for small to medium-sized pets, the soft fabric ensures warmth during chilly days. Available in multiple sizes and colors to suit different breeds, this sweatshirt adds both function and cuteness to your pet\'s wardrobe. Please check the size guide to ensure the best fit for your furry friend.', si1: '', si2: '', si3: '', si4: '' },





    // cat food// cat food// cat food// cat food// cat food// cat food// cat food// cat food// cat food// cat food// cat food// cat food
    { id: 49,category:'cat food', title: 'Royal Canin Indoor Adult Dry Cat Food, 15 lb bag', price: 67.99, image: '', description: 'This dog food formula features chicken meal as the primary protein, combined with wholesome grains like brown rice, corn, and rice for balanced energy. It includes chicken fat for flavor and essential fatty acids, along with pea fiber and beet pulp for healthy digestion. Enriched with anchovy oil for omega-3s, dried egg product, and key vitamins like A, C, D, and E, it supports immune health and overall wellness. Additional nutrients like taurine and L-carnitine promote heart and muscle health, while natural preservatives and rosemary extract ensure freshness. Suitable for dogs of all sizes and breeds.', si1: '', si2: '', si3: '', si4: '' },
    { id: 50,category:'cat food', title: 'Royal Canin Adult Feline Health Nutrition Instinctive Thin Slices in Gravy Canned Wet Cat Food', price: 26.18, image: '', description: 'Water sufficient for processing, pork by-products, chicken by-products, chicken liver, pork liver, salmon, wheat flour, wheat gluten, gelatin, pork plasma, powdered cellulose, natural flavors, modified corn starch, calcium sulfate, guar gum, potassium chloride, sodium tripolyphosphate, carrageenan, taurine, vitamins [DL-alpha tocopherol acetate (source of vitamin E), thiamine mononitrate (vitamin B1), niacin supplement, biotin, D-calcium pantothenate, pyridoxine hydrochloride (vitamin B6), riboflavin supplement, folic acid, vitamin B12 supplement, vitamin D3 supplement], trace minerals [zinc proteinate, zinc oxide, ferrous sulfate, copper sulfate, manganous oxide, sodium selenite, calcium iodate], choline chloride.', si1: '', si2: '', si3: '', si4: '' },
    { id: 51,category:'cat food', title: 'Royal Canin Feline Health Nutrition Mother & Babycat Ultra Soft Mousse in Sauce Canned Cat Food, 3 oz can (24-count)', price: 54.76, image: '', description: 'Water sufficient for processing, chicken, chicken liver, pork by-products, powdered cellulose, wheat gluten, rice flour, corn starch, natural flavors, fish oil, calcium caseinate, mannan-oligosaccharides, tetrapotassium pyrophosphate, calcium carbonate, carrageenan, fructo-oligosaccharides, guar gum, taurine, sodium tripolyphosphate, Vitamins [DL-alpha tocopherol acetate (source of vitamin E), L-ascorbyl-2-polyphosphate (source of vitamin C), thiamine mononitrate (vitamin B1), niacin supplement, biotin, D-calcium pantothenate, riboflavin supplement (vitamin B2), pyridoxine hydrochloride (vitamin B6), vitamin B12 supplement, folic acid, vitamin D3 supplement], choline chloride, magnesium oxide, Trace Minerals [zinc proteinate, zinc oxide, iron sulfate, copper sulfate, manganous oxide, sodium selenite, calcium iodate], marigold extract (Tagetes erecta L.), L-carnitine.', si1: '', si2: '', si3: '', si4: '' },
    { id: 52,category:'cat food', title: 'Wellness Complete Health Gravy & Minced Adult Wet Cat Food, Natural, Protein-Rich, Grain-Free, 3 Ounce , 24 Pack, (Chicken & Turkey Lovers Variety Pack)', price: 41.76, image: '', description: 'This pet food blend features high-quality proteins from minced turkey, chicken, and chicken liver, enriched with broths for flavor and hydration. It includes nutritious vegetables like carrots, tomatoes, and peas, plus dried egg for added protein. Guar gum ensures texture, while fish and sunflower oils provide essential fatty acids. Cranberries and dried chicory root aid digestion and antioxidant support. Ground flaxseed adds omega-3s, and minerals like zinc, iron, and copper support overall health. Fortified with a full range of vitamins (A, B-complex, C, D, E) and taurine for heart and vision health, it’s a wholesome choice for dogs.', si1: '', si2: '', si3: '', si4: '' },
    { id: 53,category:'cat food', title: 'Purina Friskies Pate Wet Cat Food Variety Pack Seafood and Chicken Pate Favorites 40ct VP - (Pack of 40) 5.5 oz. Cans', price: 29.48, image: '', description: 'Meaty Bits Gourmet Grill in Gravy is a rich pet food blend made with poultry, liver, and meat by-products, combined with wheat gluten, soy flour, and corn starch for texture. It contains essential nutrients like taurine, vitamins (A, B-complex, D, E), and minerals (zinc, iron, copper) for health support. This food is enhanced with natural and artificial flavors, calcium phosphate for bone health, and potassium chloride for electrolyte balance. Available in various flavors like chicken, beef, and poultry, it offers a delicious and balanced meal for pets, with added color and fortified with essential nutrients like biotin and folic acid for overall well-being.', si1: '', si2: '', si3: '', si4: '' },
    { id: 54,category:'cat food', title: 'ORIJEN Original Cat, Grain Free Dry Cat Food for All Life Stages, with WholePrey Ingredients, 12lb', price: 69.99, image: '', description: 'Chicken, turkey, whole herring, turkey giblets (liver, heart, gizzard), salmon, dehydrated chicken, dehydrated turkey, dehydrated salmon, dehydrated chicken liver, dehydrated egg, whole red lentils, whole pinto beans, whole green lentils, chicken liver, eggs, chicken fat, natural chicken flavor, whole navy beans, whole chickpeas, whole peas, pollock oil, lentil fiber, chicken hearts, choline chloride, whole cranberries, dried kelp, mixed tocopherols (preservative), vitamin E supplement, zinc proteinate, whole pumpkin, whole butternut squash, collard greens, whole apples, whole pears, thiamine mononitrate, copper proteinate, niacin, pyridoxine hydrochloride, dried Bacillus coagulans fermentation product, dried chicory root, turmeric, sarsaparilla root, althea root, rosehips, juniper berries, citric acid (preservative), rosemary extract.\n', si1: '', si2: '', si3: '', si4: '' },
    { id: 55,category:'cat food', title: 'Fancy Feast Gems Pate Premium Wet Cat Food Mousse With Tuna and a Halo of Savory Gravy Cat Food', price: 15.76, image: '', description: 'Chicken Broth, Chicken, Liver,meat By-product, Tuna, Tapioca Starch-modified, Glycine, Sodium Tripolyphosphate, Natural Flavors, MINERALS [Potassium Chloride, Magnesium Sulfate, Zinc Sulfate, Iron Sulfate, Manganese Sulfate, Copper Sulfate, Calcium Iodate], Locust Bean Gum, Guar Gum, Caramel Color, Carrageenan,taurine, Methyl Cellulose, L-ascorbic Acid,VITAMINS [Vitamin E Supplement, Niacin (Vitamin B-3), Thiamine Mononitrate (Vitamin B-1), Calcium Pantothenate (Vitamin B-5), Riboflavin Supplement (Vitamin B-2), Pyridoxine Hydrochloride (Vitamin B-6), Folic Acid (Vitamin B-9), Vitamin A Supplement, Menadione Sodium Bisulfite Complex (Vitamin K), Biotin (Vitamin B-7), Vitamin B-12 Supplement], Choline Chloride B638424\n', si1: '', si2: '', si3: '', si4: '' },
    { id: 56,category:'cat food', title: 'Fancy Feast Purina Petites Kitten Tender Pate Gourmet Wet Kitten Food Variety Pack - 12 ct. Tub', price: 0, image: '', description: 'Tender Entrée Patés come in chicken and salmon varieties, featuring a mix of high-quality proteins like chicken, liver, meat by-products, and fish, with flavorful broths and natural and artificial flavors. Both recipes include milk, taurine for heart health, and essential minerals such as potassium chloride, magnesium proteinate, zinc, iron, manganese, copper, and iodine. They also contain a full spectrum of vitamins including A, D3, E, B-complex, biotin, folic acid, and thiamine to support overall wellness. Guar gum provides texture, while tricalcium phosphate supports bone health. Salt and choline chloride round out the nutrient profile. These smooth paté formulas offer a tasty, nourishing meal for pets.', si1: '', si2: '', si3: '', si4: '' },
    { id: 57,category:'cat food', title: 'Purina Fancy Feast Grilled Wet Cat Food Seafood Collection in Wet Cat Food Variety Pack - (Pack of 24) 3 oz. Cans', price: 0, image: '', description: 'Grilled Seafood Feast in Gravy: Fish Broth, Ocean Fish, Wheat Gluten, Liver, Meat By-Products, Chicken, Corn Starch-Modified, Artificial and Natural Flavors, Corn Oil, Shrimp, Salt, Tricalcium Phosphate, Soy Protein Concentrate, Added Color, Potassium Chloride, Choline Chloride, Taurine, Magnesium Sulfate, Mono and Dicalcium Phosphate, Red 3, Thiamine Mononitrate, Vitamin E Supplement, Zinc Sulfate, Ferrous Sulfate, Niacin, Calcium Pantothenate, Vitamin A Supplement, Copper Sulfate, Menadione Sodium Bisulfite Complex (Source of Vitamin K Activity), Manganese Sulfate, Pyridoxine Hydrochloride, Riboflavin Supplement, Vitamin B-12 Supplement, Biotin, Folic Acid, Vitamin D-3 Supplement, Potassium Iodide. C-6928 Grilled Tuna Feast in Gravy: Fish Broth, Tuna, Potassium Iodide. C-6929. Grilled Salmon Feast in Gravy: Fish Broth, Salmon, Potassium Iodide. C-6926.\n', si1: '', si2: '', si3: '', si4: '' },
    { id: 58,category:'cat food', title: 'Purina Fancy Feast Gourmet Gravy Wet Cat Food, Petites Seared Salmon With Spinach Entree - (Pack of 12) 2.8 oz. Tubs', price: 0, image: '', description: 'Salmon Broth, Salmon, Wheat Gluten, Liver, Meat By-products, Chicken, Corn Starch-modified, Spinach, Glycine, Salt, Tricalcium Phosphate, Soy Protein Concentrate, Natural Flavor, Minerals (Potassium Chloride, Magnesium Proteinate, Zinc Sulfate, Ferrous Sulfate, Manganese Sulfate, Copper Sulfate, Potassium Iodide), Taurine, Choline Chloride, Vitamins (Thiamine Mononitrate, Vitamin E Supplement, Niacin, Calcium Pantothenate, Vitamin A Supplement, Menadione Sodium Bisulfite Complex, Pyridoxine Hydrochloride, Riboflavin Supplement, Vitamin B-12 Supplement, Biotin, Folic Acid, Vitamin D-3 Supplement).\n', si1: '', si2: '', si3: '', si4: '' },
    { id: 59,category:'cat food', title: 'IAMS Proactive Health Adult Sensitive Digestion & Skin Dry Cat Food with Turkey, 13 lb. Bag', price: 33.98, image: '', description: 'Turkey, Chicken By-Product Meal, Ground Whole Grain Corn, Brewers Rice, Chicken Meal, Corn Gluten Meal, Chicken Fat (preserved with Mixed Tocopherols), Ground Sorghum, Dried Plain Beet Pulp, Fish Oil (preserved with Mixed Tocopherols), Natural Flavor, Sodium Bisulfate, Caramel Color, Fructooligosaccharides, Dried Egg Product, Potassium Chloride, Brewers Dried Yeast, Choline Chloride, Vitamins [Vitamin E Supplement, Niacin, Ascorbic Acid, Vitamin A Acetate, Calcium Pantothenate, Biotin, Thiamine Mononitrate (source of Vitamin B1), Pyridoxine Hydrochloride (source of Vitamin B6), Vitamin B12 Supplement, Riboflavin Supplement (source of Vitamin B2), Inositol, Vitamin D3 Supplement, Folic Acid], Taurine, Calcium Carbonate, Minerals [Zinc Oxide, Manganese Sulfate, Copper Sulfate, Potassium Iodide], L-Carnitine, Rosemary Extract\n', si1: '', si2: '', si3: '', si4: '' },
    { id: 60,category:'cat food', title: 'IAMS PROACTIVE HEALTH Healthy Senior Dry Cat Food with Chicken Cat Kibble, 16 lb. Bag', price: 33.98, image: '', description: 'Chicken, Chicken By-Product Meal (source of Glucosamine and Chondroitin Sulfate), Corn Grits, Ground Whole Grain Corn, Dried Plain Beet Pulp, Natural Flavor, Dried Egg Product, Brewers Dried Yeast, Chicken Fat (preserved with Mixed Tocopherols), Potassium Chloride, Fish Oil (preserved with mixed Tocopherols), Choline Chloride, Fructooligosaccharides, Vitamin E Supplement, Calcium Carbonate, Taurine, Vitamins (Niacin, Ascorbic Acid, Vitamin A Acetate, Calcium Pantothenate, Biotin, Thiamine Mononitrate (source of vitamin B1), Pyridoxine Hydrochloride (source of vitamin B6), Vitamin B12 Supplement, Riboflavin Supplement source of vitamin B2), Inositol, Vitamin D3 Supplement, Folic Acid), Zinc Oxide, Manganese sulfate, L-Carnitine, Copper Sulfate, Potassium Iodide, Rosemary Extract\n', si1: '', si2: '', si3: '', si4: '' },






    //cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys//cat toys
    { id: 61,category:'cat toys', title: 'Potaroma Smart Sensor Cat Laser Toys Interactive, Motion Activated Truly Random Trjajectory, Clamp Design, Automatic Chargeable Kitten Toy Indoor Exercise', price: 16.99, image: '', description: 'This cat laser toy features the first truly random trajectory using a built-in specular reflection mechanism that mimics real prey movement, keeping cats entertained and stimulating their hunting instincts. It offers motion-activated play, running for 5 minutes when pet activity is detected, then entering standby or powering off when inactive. With multiple modes like sensing and timer, and adjustable speed and range via tilt, it suits all activity levels. The dual-clamp design prevents knock-overs and allows secure attachment to chairs, doors, and more. Its energy-efficient design, using mirror adjustments instead of motors, extends battery life to 5–10 days per charge, and it can be used while charging for non-stop fun.', si1: '', si2: '', si3: '', si4: '' },
    { id: 62,category:'cat toys', title: 'LUCKITTY Geometric Straight Cat Tunnel with Plush Inside,Cats Toys Collapsible Tunnel Tube with Balls, for Rabbits, Kittens, Ferrets,Puppy, Diameter 9.8 Inch', price: 19.90, image: '', description: 'This cat tunnel features a soft flannel interior for comfort and a waterproof, durable oxford cloth exterior for long-lasting use. Measuring 47.2 inches in length and 9.8 inches in diameter, it offers ample space for big cats to move freely. The strong, sprung steel frame ensures the tunnel pops out and retracts easily for quick setup and compact storage. Designed for both fun and functionality, it provides a cozy hideout and play area for cats of all sizes, combining comfort, durability, and portability in one.', si1: '', si2: '', si3: '', si4: '' },
    { id: 63,category:'cat toys', title: 'uahpet Natural Feather Cat Toys for Indoor Cats Retractable Kitten Wand 60inch Safe Hunting Distance Interactive Toys for Kittens with 4Pcs Senses Replacement Teasers Arouse Desire to Hunt', price: 0, image: '', description: 'The uahpet cat wand toy mimics real hunting with a 60-inch reach, letting cats jump, chase, and play freely. It includes four natural teaser refills that stimulate your cat’s senses and instincts. Lightweight like a pen, the durable carbon fiber rod is easy to handle for longer play. It helps reduce destructive behavior, night activity, and obesity while keeping cats active and happy. Safe, non-toxic materials make it lick-friendly, and the extended length protects your hands during play. Includes wand and four refills: bird, dragonfly, cocoon, and butterfly.', si1: '', si2: '', si3: '', si4: '' },
    { id: 64,category:'cat toys', title: 'Potaroma Cat Toys Flapping Bird (No Flying), Lifelike Sandpiper Chirp Tweet, Rechargeable Touch Activated Kitten Toy Interactive Cat Exercise Toys for All Breeds Cat Kicker Catnip Toys 4.0"', price: 16.78, image: '', description: 'This interactive sandpiper cat toy provides fun for both self-play and bonding with owners. It flaps and chirps like a real bird when touched, thanks to a built-in motion sensor, engaging your cat’s instincts to kick, chase, and play. Made of soft plush with a hidden catnip pouch, it encourages movement and exercise while offering cozy snuggles. The realistic sandpiper design keeps cats entertained and reduces boredom when you\'re away. USB rechargeable and easy to clean with a removable mechanism, it’s a hassle-free, durable, and fun toy for all cats.', si1: '', si2: '', si3: '', si4: '' },
    { id: 65,category:'cat toys', title: 'Interactive Cat Toys - Retractable Wand Toy and Feather Toys Refills for Indoor Cats to Chase and Exercise', price: 0, image: '', description: 'This interactive cat wand toy combines feathers and string to trigger your cat\'s natural hunting instincts, keeping them entertained and active. Ideal for indoor cats, it encourages exercise, reduces boredom, and strengthens the bond between pets and owners. The telescopic wand extends up to 38.9" with a 23.6" string, covering a wide play area while allowing you to relax during playtime. The set includes 2 wands, 9 feather/worm attachments, and extra strings for long-lasting fun. Made from safe, natural feathers and durable materials, it\'s lightweight, flexible, and easy to store. Best used under supervision, this toy is a fun, safe way to engage your cat physically and mentally.', si1: '', si2: '', si3: '', si4: '' },
    { id: 66,category:'cat toys', title: 'Andiker Cat Spiral Spring, 12 Pc Cat Creative Toy to Kill Time and Keep Fit Interactive Cat Toy Sturdy Heavy Plastic Spring Colorful Springs Cat Toy for Swatting, Biting, Hunting Kitten Toys', price: 5.39, image: '', description: 'These colorful cat spring toys come in four bright shades—yellow, green, pink (or red), and blue—designed to catch your cat\'s eye and spark curiosity. Made from durable 1.8mm thick plastic, they’re safe for biting and built to last. The bouncy, lightweight design encourages cats to chase, pounce, and chew, helping them stay active and entertained. You can toss the springs to engage your cat in interactive play or let them enjoy solo fun. With smooth edges for safety and soft elasticity for extra bounce, these toys are a great way to stimulate your cat’s natural instincts.', si1: '', si2: '', si3: '', si4: '' },
    { id: 67,category:'cat toys', title: 'Potaroma Cat Toys Saury Fish, 3 Pack, Catnip Crinkle Sound, Soft and Durable, Interactive Kitten Kicker for Indoor Kitty Exercise 9.4 Inches for All Breeds\n', price: 9.96, image: '', description: 'These soft plush catnip fish kicker toys are made with baby-level cotton, offering a cozy and chewable companion for your feline. Each toy is filled with 100% organic catnip to excite and engage your cat in playful, interactive fun. Designed to stimulate natural instincts like chasing, chewing, and pouncing, they help relieve boredom and support healthy development. Available in three bright colors—green, yellow, and orange—they easily attract attention and are perfectly sized for kittens to hug, kick, or scratch. A great gift for cats and backed by reliable customer support.', si1: '', si2: '', si3: '', si4: '' },
    { id: 68,category:'cat toys', title: 'Fashion\'s Talk Cat Toys Variety Pack for Kitty 20 Pieces', price: 9.99, image: '', description: 'This 20-piece cat toy bundle is a fun, randomly assembled mix that may vary in styles and colors, keeping playtime fresh and exciting. It includes a variety of toys like feather wands, catnip mice, rattle toys, and balls to keep your cat entertained and active when you\'re away. Designed to stimulate energy release and satisfy hunting instincts, these toys make a great gift for holidays, birthdays, or everyday fun. While strong, they’re not indestructible—always supervise play and replace toys if damaged. A playful and thoughtful treat for your feline friend.', si1: '', si2: '', si3: '', si4: '' },
    { id: 69,category:'cat toys', title: 'Catstages Tower of Tracks Interactive 3-Tier Cat Track Toy with Spinning Balls, Orange', price: 11.99, image: '', description: 'The upgraded Tower of Tracks now includes six vibrant 1.5" balls instead of three at no extra cost, offering double the fun for your feline. This three-level interactive toy encourages mental stimulation, physical exercise, and satisfies natural hunting instincts as cats bat, swat, and chase the spinning balls. Ideal for solo or multi-cat households, it features a top safety bar to prevent paws from getting stuck. With its sturdy construction and non-slip base, it’s built for energetic play, making it a safe and engaging addition to any cat’s toy collection.', si1: '', si2: '', si3: '', si4: '' },
    { id: 70,category:'cat toys', title: 'Cat Dancer Products 101 Interactive Cat Toy, Brown', price: 3.99, image: '', description: 'The original Cat Dancer interactive cat toy features spring steel wire and rolled cardboard, creating an irresistible lure that mimics the erratic movements of real prey. Designed to trigger your cat’s natural hunting instincts, this simple yet effective toy delivers endless entertainment. It’s been home-tested by over 8 million cats and beloved by both felines and their owners for its ability to keep cats active and engaged. Lightweight, durable, and easy to use, it offers interactive fun and bonding time. Perfect for indoor cats, it helps reduce boredom and encourages exercise.', si1: '', si2: '', si3: '', si4: '' },
    { id: 71,category:'cat toys', title: '5Pcs Bite Resistant Catnip Toy for Cats,Catnip Filled Cartoon Mice Cat Teething Chew Toy', price: 0, image: '', description: 'This cat chew toy is the perfect gift, filled with natural catnip and made from breathable fabric to easily attract your cat\'s interest. Crafted with durable cotton linen and fine stitching, it’s bite-resistant and built to last. Stuffed with soft PP cotton and catnip, it’s safe and high quality for indoor or outdoor play. Ideal for reducing boredom and separation anxiety, it keeps your pet entertained and engaged. If you’re not satisfied, we offer a 100% refund or replacement—just contact us with any questions.', si1: '', si2: '', si3: '', si4: '' },






    //health and supplies cat//health and supplies cat//health and supplies cat//health and supplies cat//health and supplies cat//health and supplies cat
    { id: 72,category:'health and supplies cat', title: 'Advantage II Large Cat Vet-Recommended Flea Treatment & Prevention | Cats Over 9 lbs. | 2-Month Supply', price: 33.58, image: '', description: 'Advantage II for Large Cats is a vet-recommended, fragrance-free topical flea treatment for cats over 9 lbs. and 8 weeks old. This easy-to-apply, waterproof formula requires no prescription and provides total protection by killing adult fleas, larvae, and eggs on contact. It begins working within 12 hours and offers continuous flea control for up to 30 days, with no need for pills or messy applications.', si1: '', si2: '', si3: '', si4: '' },
    { id: 73,category:'health and supplies cat', title: 'Flea and Tick Prevention for Cats, 200 Soft Chews for Fleas Treatment for Cats, Natural Cat Oral Flea Chewables Support Supplement, Flea and Tick Chews for All Breeds & Sizes', price: 0, image: '', description: 'This natural flea treatment for cats comes in soft chews made with gentle, effective ingredients like coconut oil, flaxseed, and brewer’s yeast, offering flea, tick, and mosquito defense without harsh chemicals. Each bottle contains 200 chews, providing up to three months of protection while supporting your cat’s skin, coat, and immune health. Enriched with fish oil and B vitamins, the chews reduce itching and promote a shiny coat. Suitable for all breeds and ages, they offer a mess-free alternative to sprays or drops—just serve as a treat or mix into food for easy, consistent protection.', si1: '', si2: '', si3: '', si4: '' },
    { id: 74,category:'health and supplies cat', title: 'PetArmor Plus Flea and Tick Prevention for Cats, Cat Flea and Tick Treatment, 3 Doses, Waterproof Topical, Fast Acting, Cats Over 1.5 lbs', price: 24.93, image: '', description: 'PetArmor Plus is a waterproof, vet-quality flea and tick topical treatment for cats that kills fleas, flea eggs, larvae, ticks, and chewing lice for up to 30 days. Using the same active ingredients as FRONTLINE Plus (fipronil and (S)-methoprene), it begins working within 24 hours and effectively breaks the flea life cycle to prevent re-infestation. This easy-to-apply treatment also protects against multiple types of ticks, including those that may transmit Lyme disease. Each pack includes three monthly applications for long-lasting, reliable protection.', si1: '', si2: '', si3: '', si4: '' },
    { id: 75,category:'health and supplies cat', title: 'Flea and Tick Prevention for Cats, Repellent, Treatment, and Control, Fast Acting Waterproof Topical Drops for Cats Over 3.5 lbs, 3 Month Dose', price: 0, image: '', description: 'NEXTSTAR flea and tick treatment for cats starts killing fleas and ticks within 15 minutes and offers fast, vet-strength protection without a prescription. This easy-to-apply topical provides 30 days of waterproof, long-lasting defense against fleas, ticks, mosquitoes, chewing lice, flea eggs, larvae, and pupae. It prevents reinfestation by stopping flea eggs from maturing into adults and delivers comprehensive 7-way control with just one application, keeping your cat protected and comfortable all month long.', si1: '', si2: '', si3: '', si4: '' },
    { id: 76,category:'health and supplies cat', title: 'Apex Plus Cat Flea and Tick Treatment | 6-Month Supply, Over 1.5 lbs | Flea Treatment for Cats | 24-Hour Activation, Waterproof, 30-Day Protection', price: 28.99, image: '', description: 'Apex Plus flea and tick treatment for cats provides 30-day protection by killing adult fleas, ticks, eggs, and larvae, breaking the life cycle and preventing reinfestation. With powerful actives like Fipronil and (S)-methoprene (an IGR), it halts development at every stage. This topical treatment is waterproof after 24 hours and safe for cats over 1.5 lbs and 8 weeks old. Ideal for both treating existing infestations and preventing future ones, it works on contact—no need for biting, collars, or oral meds. Easy to apply and EPA-approved, it ensures reliable year-round defense.', si1: '', si2: '', si3: '', si4: '' },
    { id: 77,category:'health and supplies cat', title: 'Amazon Basics Cat Flea Treatment, Topical Solution for Large Cats Over 9 Pounds, 6 Count', price: 31.73, image: '', description: 'This fast-acting flea medication for large cats eliminates fleas within 12 hours and provides up to 4 weeks of continuous protection per application. Specially formulated for cats over 9 pounds, it kills reinfesting fleas within 2 hours to effectively disrupt the flea lifecycle. The topical formula offers targeted, reliable flea control without the hassle of expiration dates, ensuring long-lasting effectiveness and peace of mind for pet owners.', si1: '', si2: '', si3: '', si4: '' },
    { id: 78,category:'health and supplies cat', title: 'Amazon Basics Topical Flea Treatment for Medium Cats (5-9 Pounds), 6 Count (Previously Solimo)', price: 31.73, image: '', description: 'This topical flea treatment for cats provides up to 30 days of protection against fleas, eggs, and larvae with each monthly application. Designed for use on dry skin between the shoulder blades, it uses a dual-ingredient formula featuring Imidacloprid and Pyriproxyfen for effective flea control. Packaging may vary between Solimo and Amazon Basics, but the quality and efficacy remain the same.', si1: '', si2: '', si3: '', si4: '' },
    { id: 79,category:'health and supplies cat', title: 'Only Natural Pet EasyDefense Flea & Tick Cat Collar - Feline Flea Collars Biting Insect Control - Pet Care That Protects up to 4 Months - for Cats (2 Pack)', price: 25.93, image: '', description: 'This breakaway flea and tick collar provides fast-acting, on-the-spot protection that lasts up to 4 months, offering water-resistant, long-term defense. Made with natural ingredients like Geraniol, Citronella, and Cinnamon, it’s a gentle, effective solution against fleas, ticks, and mosquitoes. The one-size-fits-all design can be trimmed to fit comfortably, ensuring easy, stress-free application. Just fasten it around your cat’s neck, leave space for two fingers, and replace every four months for continued protection and peace of mind.', si1: '', si2: '', si3: '', si4: '' },
    { id: 80,category:'health and supplies cat', title: 'Flea and Tick Collar for Cats, Natural Plant-Based Ingredients for Treatment and Prevention, Safe and Waterproof, with Free Flea Comb, Tick Tweezer, and Treatment Prevention Drops, 13.8 in (2 Packs)', price: 0, image: '', description: 'This cost-effective pest control kit includes two 6-month natural flea collars, three months of flea treatment drops, a flea comb, tick tweezers, and a manual, offering complete protection for your pet. Made from plant-based essential oils, it\'s a gentle, natural solution designed to repel (not kill) fleas and ticks. Ideal for pets without sensitive skin, this bundle prioritizes safety and value without compromising on effectiveness. A dedicated support team is available to guide you in using the products for optimal results.', si1: '', si2: '', si3: '', si4: '' },
    { id: 81,category:'health and supplies cat', title: 'Hartz UltraGuard Pro Topical Flea & Tick Prevention for Cats & Kittens, Over 5 lbs 6 Monthly Treatments', price: 0, image: '', description: 'This flea and tick treatment kills fleas, larvae, eggs, and deer ticks on contact while repelling mosquitoes before they bite. With dual insect growth regulators, it prevents reinfestation for a full month per dose. The fast-acting formula spreads naturally across your cat’s skin for full-body protection from head to tail. Easy to apply with the Pro-cision Flo applicator, it works gently through both long and short fur. The pack includes six monthly treatments, providing up to six months of continuous protection.', si1: '', si2: '', si3: '', si4: '' },







    //clothes cat//clothes cat//clothes cat//clothes cat//clothes cat//clothes cat//clothes cat//clothes cat
    { id: 82,category:'clothes cat', title: 'T\'CHAQUE Sticky Hair Cat Clothes, Soft Cat Onesie Pajamas Long Sleeve Prevent Lost Hair, Kitten Surgery Recovery Suit, Anti-Shedding Shirt Outfit, Kitten Sweaters for Male & Female', price: 25.39, image: '', description: 'This long-sleeved cat onesie, made from professional hair-sticking material, helps catch shedding hair during seasonal changes, saving time on cleaning fur from clothes, furniture, and carpets. Designed for all pet sizes and available in various colors, it provides full coverage to reduce shedding while keeping cats comfortable and free to move. Ideal for use as indoor wear or pajamas, it keeps both your cat and home cleaner with less effort.', si1: '', si2: '', si3: '', si4: '' },
    { id: 83,category:'clothes cat', title: 'Cat Suit for After Surgery, Anti Licking Breathable Cat Outfits for Female Cats Neuter Recovery Suit Male E-Collar Alternative Kitten Onesie for Cats Abdominal Wounds Or Skin Diseases', price: 6.49, image: '', description: 'This soft, breathable cat onesie is ideal for all pet sizes and colors, offering a comfortable alternative to cones after surgery. It helps reduce anxiety, supports healing from wounds or weaning, and prevents licking of incisions, making recovery easier. Designed with adjustable neckbands and stretchy straps for a snug fit, it allows your cat to move, eat, and use the litter box normally. Fun patterns keep your pet stylish while healing. Easy to wash and reusable, it’s a thoughtful and practical recovery suit for both male and female cats.', si1: '', si2: '', si3: '', si4: '' },
    { id: 84,category:'clothes cat', title: 'QWINEE Basic Dog Hoodie, Dog Warm Jacket, Cat Apparel, Dog Shirt, Dog Clothes', price: 14.99, image: '', description: 'This stretchy, warm hoodie is easy to put on and take off, keeping pets cozy during colder days. Designed with a stylish hoodie and short sleeves, it adds a fashionable touch while providing comfort and warmth. Suitable for all colors and sizes of small to medium pets, the hoodie exudes energy and charm. Ideal for daily wear, it ensures a snug fit and allows free movement. Be sure to measure your pet’s chest and check the size chart before ordering to ensure the best fit.', si1: '', si2: '', si3: '', si4: '' },
    { id: 85,category:'clothes cat', title: 'QWINEE Dinosaur Hoodie Warm Jacket Christmas Halloween Costume Clothes for Puppy Kitten', price: 14.99, image: '', description: 'This stretchy, warm hoodie features a fun dinosaur design with a hood and short sleeves to keep pets cozy and stylish in cold weather. Easy to put on and take off, it adds playful charm and comfort for pets of all colors and sizes. Ideal for small to medium breeds, it allows free movement while showing off your pet’s personality. Be sure to measure your pet’s chest and check the size chart before ordering for the best fit.', si1: '', si2: '', si3: '', si4: '' },
    { id: 86,category:'clothes cat', title: 'Traditional Culture Sphynx Hairless Cat Cotton T-Shirts Clothes Pet Sweater Cat Vest Pet Clothes Kitten Shirts', price: 16.99, image: '', description: 'Designed for sensitive, hairless cats like Sphynx, Devon Rex, and Peterbald, this soft, comfy shirt features quality stitching, a button-up front for easy wear, and a loose waist for active comfort. Medium thickness makes it perfect for all seasons—breathable in summer, warming in winter when layered. Fashionable patterns add charm for daily wear, photos, or holidays. Crafted to fit feline body lines, it’s ideal for indoor or outdoor use. Sizes range from S to XXL for cats of various weights—order one size up for non-hairless cats.', si1: '', si2: '', si3: '', si4: '' },
    { id: 87,category:'clothes cat', title: 'Turtleneck Sweater for Sphynx Cat Soft Thick Double-Sided Fleece Cat Clothes Winter Warm Outfit Coat for Hairless Cats', price: 14.99, image: '', description: 'This handmade, super soft and warm winter sweater is designed specifically for hairless cats like Sphynx, Devon Rex, and Peterbald, offering thick fleece protection for sensitive skin. The elastic, double-sided fleece provides comfort and warmth, perfect for winter, keeping your cat cozy and safe from the cold. Available in sizes S to XXL, the sweater is adjustable to fit various weights and is great for indoor or outdoor wear. With a cute design, it’s ideal for everyday use, photos, and holidays. The sweater is easy to layer with other outfits for extra warmth and comfort.', si1: '', si2: '', si3: '', si4: '' },
    { id: 88,category:'clothes cat', title: 'Turtleneck Sphynx Cat Winter Clothes, Double-Sided Fleece Jacket with Zipper, Sweater for Sphynx Cat Winter Warm Outfit Coat for Hairless Cats', price: 19.99, image: '', description: 'This handmade, super soft, and thick fleece winter sweater is designed specifically for hairless cats like Sphynx, Devon Rex, and Peterbald, providing warmth and protection for sensitive skin. Made from slightly elastic granular fleece, it keeps your cat cozy and safe from the cold while offering comfort and flexibility for play. Available in sizes S to XXL, it\'s perfect for winter, with options like Pink, Blue, Grey, and Brown. The sweater’s cute design suits everyday wear, photos, and holiday occasions, offering both warmth and style for your furry friend. Ideal for indoor and outdoor use, it’s a must-have for hairless cats.', si1: '', si2: '', si3: '', si4: '' },
    { id: 89,category:'clothes cat', title: 'UPVOX Christmas Pet Scarf for Dogs and Cats Warm Plush Neck with Star Design Lightweight and Washable for Holiday Dress Up', price: 0, image: '', description: 'This pet Christmas costume features a colorful, simple, and stylish design perfect for your pet’s holiday dress-up. The lightweight, soft, and durable neck circle is made of cloth, ensuring comfort and breathability for your cat or dog. Easy to wear and washable, it adds a festive touch, creating a strong holiday atmosphere. Ideal for both cats and dogs, this costume is a lovely, beautiful accessory that your pet will love wearing during Christmas celebrations. Available in various sizes and colors to fit all pets.', si1: '', si2: '', si3: '', si4: '' },
    { id: 90,category:'clothes cat', title: 'YARNOW 2Pcs Tiger Pet Hat Funny Cat Puppy Headgear Cosplay Headwear for Parties Everyday Wear Comfortable Stylish Design for Photo Shoots Play Dates', price: 9.79, image: '', description: 'This skin-friendly and comfortable pet hat is perfect for themed parties, cosplay, or any festive occasion. Ideal for both cats and dogs, it’s easy to put on and take off, helping your pet stand out as fashionable and adorable. Whether it\'s for a pet party, holiday, birthday, or family portrait, this decorative headwear adds a unique touch to your pet\'s look. It fits various sizes of pets securely, staying in place without slipping. Available in multiple colors, this hat makes your pet look charming and attractive for any event.', si1: '', si2: '', si3: '', si4: '' },
    { id: 91,category:'clothes cat', title: 'T\'CHAQUE Cat Pajamas - Soft Cat Clothes& Shirts & Pajamas with Sleeves, Stretchy Sweater, Pullover Kitten Clothes', price: 15.39, image: '', description: 'This soft and comfortable cat sweater is made of high-quality velvet fabric, offering a breathable and smooth texture for ultimate comfort. Designed specifically for cats, it features a stretchy material that ensures a snug fit, making dressing quick and easy. The sweater is easy to clean, supporting both hand and machine washing without losing shape. Its front leg sleeve design stays securely in place, keeping your cat cozy and warm. The loose fit at the waist allows freedom of movement, enabling your cat to use the litter tray without hassle while maintaining comfort and flexibility. Available in various sizes and colors for all cats.', si1: '', si2: '', si3: '', si4: '' },
    { id: 92,category:'clothes cat', title: 'Cat Halloween Costumes - Lion Mane Wig for Cats & Puppies, Adjustable Pet Cosplay Apparel Kitten Outfits for Halloween Christmas Cat Birthday Party', price: 0, image: '', description: 'Transform your cat into the king of the jungle with this Halloween lion costume! Made from high-quality fiber fur, the soft and fluffy lion mane is comfortable, durable, and easy to clean. The Velcro closure ensures a secure fit for most cats and small dogs with neck circumferences between 10-12 inches (26-30 cm). Perfect for Halloween, costume parties, cosplay, or photoshoots, this costume also adds warmth in colder months. Your pet will stand out with its fierce lion look. Available in various sizes and colors, and supported by excellent customer service for any issues.', si1: '', si2: '', si3: '', si4: '' },
    { id: 93,category:'clothes cat', title: 'AIERSA Pet Hair Removal Tool, Static Removal Gloves for Pet Hair, Dog and Cat Hair Remover Set for Couch, Clothes, Car Detailing, Carpet, Bed, Bedding, Furniture', price: 9.99, image: '', description: 'These reusable pet hair removal gloves are perfect for cleaning sofas, beds, car seats, and carpets. Simply slip them on and swipe to gather pet hair into strips, quickly cleaning large areas with minimal effort. Unlike lint rollers, these gloves require no refills, making them an eco-friendly and cost-effective choice. Made from soft, flexible fabric, they are gentle on both pets and furniture, effectively removing hair without damaging fabrics. Ideal for soft surfaces like clothes, sofas, and bedding, they provide a versatile solution for homes with pets. Easy to clean and economical, just wash after use to keep them ready for the next cleaning session.', si1: '', si2: '', si3: '', si4: '' },
  ];
  

  }

  productLIst(){
  return this.products;
  }


  
  getTwoProductsPerCategory(): ProduitModel[] {
    const result: ProduitModel[] = [];
    const categoryMap: { [key: string]: ProduitModel[] } = {};
  
    // Grouper les produits par catégorie
    this.products.forEach(product => {
      if (!categoryMap[product.category]) {
        categoryMap[product.category] = [];
      }
      categoryMap[product.category].push(product);
    });
  
    // Ajouter les deux premiers produits de chaque catégorie
    Object.keys(categoryMap).forEach(category => {
      result.push(...categoryMap[category].slice(0, 2));
    });
  
    return result;
  }
  
}
